name: Deploy
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      image_version:
        description: Docker Image Version
        required: true
        type: string

  workflow_dispatch:
    inputs:
      image_version:
        description: Docker Image Version
        required: true
        type: string


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  set-enviroment: 
    name: Set enviroment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.enviroment }}

    steps:
      - name: Set enviroment
        id: set-env
        uses: turali7v/policy/.github/actions/set-enviroment@main

  deploy:
    name: 'Deploy'
    needs: [set-enviroment]
    environment: ${{ needs.set-enviroment.outputs.environment }}
    if: github.ref == 'refs/heads/main' 
    #&& github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy to Prod
      run: |
        echo "Deploying to production and environment=${{ needs.set-enviroment.outputs.environment }}"

  dev:
    name: 'Deploy to dev'
    needs: [set-enviroment]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    environment: ${{ needs.set-enviroment.outputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy to dev
      run: |
        echo "Deploying to dev and environment=${{ needs.set-enviroment.outputs.environment }}"