name: Deploy
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      # environment:
      #   description: Environment to Deploy
      #   required: true
      #   type: string

      image_version:
        description: Docker Image Version
        required: true
        type: string


  workflow_dispatch:
    inputs:
      # environment:
      #   description: Environment to Deploy
      #   required: true
      #   type: choice
      #   options:
      #     - prod

      image_version:
        description: Docker Image Version
        required: true
        type: string


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "TARGET_ENV=${{ github.ref }}" >> $GITHUB_ENV

      - name: Deploy to Dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          echo "Deploying to dev environment"

      - name: Deploy to Prod
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          echo "Deploying to production"
    

      # - name: Install Helm
      #   run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # - name: Helm Login
      #   run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} -u a-savinski  --password-stdin

      - name: Set up Variables
        run: |
          export SHA=$(echo $(($RANDOM%(9999999-1000000+1)+1000000)))
          # echo "VERSION=$(echo ${{ inputs.image_version }}-$SHA)" >> $GITHUB_ENV
          export REPO=$(echo ${IMAGE_NAME,,})
          echo "REPO_NAME=$(echo $REPO | awk -F'/' '{print $1}')" >> $GITHUB_ENV
          echo "SERVICE_NAME=$(echo $REPO | awk -F'/' '{print $NF}' | cut -d'-' -f2)" >> $GITHUB_ENV
      
      - name: Helm Upgrade Prod
        if: github.ref == 'refs/heads/main'
        run: echo "This is prod"
      
      - name: Helm Upgrade Dev
        if: github.ref == 'refs/heads/develop'
        run: echo "This is dev environment and reponame is ${IMAGE_NAME}"

      # - name: Chart Packaging
      #   run: helm package ./chart/ --version ${{ env.VERSION }}

      # - name: Push Helm Package
      #   run: helm push *-${{ env.VERSION }}.tgz oci://${{ env.REGISTRY }}/${{ env.REPO_NAME }}/helm

      # after ci pipeline the container registry need some time to show container images
      # - name: Wait for 30 seconds
      #   run: sleep 30

      # - name: Helm Upgrade
      #   run: helm upgrade --install --namespace ${{ inputs.environment }} --set image.tag=${{ inputs.image_version }} --version ${{ env.VERSION }} ${{ env.SERVICE_NAME }} oci://${{ env.REGISTRY }}/${{ env.REPO_NAME }}/helm/${{ env.SERVICE_NAME }}

      - name: Deploy Results
        run: |
          echo Deployed Docker Image: ${{ inputs.image_version }}
          echo Helm Chart: ${{ env.VERSION }}
