name: Deploy
on:
  push:
    branches:
      - main
      - develop
  workflow_call:
    inputs:
      image_version:
        description: Docker Image Version
        required: true
        type: string

  workflow_dispatch:
    inputs:
      image_version:
        description: Docker Image Version
        required: true
        type: string


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/develop' && 'dev' || 'prod' }}
    if: github.ref == 'refs/heads/develop' || (github.event.pull_request.merged == true && github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "TARGET_ENV=${{ github.ref }}" >> $GITHUB_ENV

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploying to dev environment and $DEPLOY_ENV"

      - name: Deploy to Prod
        if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
        # if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to production and $DEPLOY_ENV"

      - name: Set up Variables
        run: |
          export SHA=$(echo $(($RANDOM%(9999999-1000000+1)+1000000)))
          # echo "VERSION=$(echo ${{ inputs.image_version }}-$SHA)" >> $GITHUB_ENV
          export REPO=$(echo ${IMAGE_NAME,,})
          echo "REPO_NAME=$(echo $REPO | awk -F'/' '{print $1}')" >> $GITHUB_ENV
          echo "SERVICE_NAME=$(echo $REPO | awk -F'/' '{print $NF}' | cut -d'-' -f2)" >> $GITHUB_ENV
      
      # - name: Helm Upgrade Prod
      #   if: github.ref == 'refs/heads/main'
      #   run: echo "This is prod"
      
      # - name: Helm Upgrade Dev
      #   if: github.ref == 'refs/heads/develop'
      #   run: echo "This is dev environment and reponame is ${IMAGE_NAME}"
